[package]
name = "plausible-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
authors = ["Todd Everett Griffin <toddgriffin@protonmail.com>"]
repository = "https://github.com/goddtriffin/plausible-rs"
homepage = "https://www.toddgriffin.me/"
description = "A Rust library for the Plausible Analytics API."
license = "MIT"
keywords = ["plausible", "analytics", "api", "http", "client"]
categories = ["web-programming"]
exclude = [
    ".idea/*",
]


[dependencies]
# tokio
tokio = { version = "1", features = ["full"] }

# http request
reqwest = { version = "0.11", default-features = false, features = [ "json", "rustls-tls" ] }
bytes = "1.0"

# serde
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.81"
